version: '3.7'
services:
  psql:
    container_name: malware_postgres
    image: postgres
    environment:
      - POSTGRES_DB=malware_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    restart: always
  malware_analysis:
    build: .
    container_name: malware_analysis_srv
    restart: always
    environment:
      - VIRUSTOTAL_APIKEY=7999f97019fda95c4565c729b137f6b51cd2afc042224eeb2485c81dab0f4187
      - CELERY_BROKER_URL=redis://localhost:6379/1
      - CELERY_RESULT_BACKEND=redis://localhost:6379/1
      - POSTGRES_DB=malware_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8001:8000"
    command: bash -c "make run"
    depends_on:
      - psql
      - redis
  redis:
    container_name: malware_redis
    image: redis
    expose:
      - "6379"
    grafana:
      image: grafana/grafana-enterprise
      container_name: grafana
      restart: always
      # if you are running as root then set it to 0
      # else find the right id with the id -u command
      user: '0'
      ports:
        - '3000:3000'
      # adding the mount volume point which we create earlier
      volumes:
        - '$PWD/data:/var/lib/grafana'
