version: '3.7'
services:
  psql:
    container_name: malware_postgres
    image: postgres
    environment:
      - POSTGRES_DB=malware_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: always
  malware_analysis:
    build: .
    container_name: malware_analysis_srv
    restart: always
    environment:
      - VIRUSTOTAL_APIKEY=7999f97019fda95c4565c729b137f6b51cd2afc042224eeb2485c81dab0f4187
      - CELERY_BROKER_URL=redis://192.168.200.2:6380/1
      - CELERY_RESULT_BACKEND=redis://192.168.200.2:6380/1
      - POSTGRES_DB=malware_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=192.168.200.2
      - POSTGRES_PORT=5433
      - DAAS_MANAGER_URL=192.168.200.2:8000
    ports:
      - "8001:8001"
    command: bash -c "make run"
    depends_on:
      - psql
      - redis
  redis:
    container_name: malware_redis
    image: redis
    ports:
      - "6380:6379"
