version: '3.7'
services:
  psql:
    container_name: malware_postgres
    image: postgres
    environment:
      - POSTGRES_DB=malware_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: always
  malware_analysis:
    build: .
    container_name: malware_analysis_srv
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://192.168.200.2:6380/1
      - CELERY_RESULT_BACKEND=redis://192.168.200.2:6380/1
      - POSTGRES_DB=malware_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=192.168.200.2
      - POSTGRES_PORT=5433
      - DAAS_MANAGER_URL=daas.npd-co.com
      - SCAN_DAILY_RATE_LIMIT=200
      - ALLOWED_MALBEHAVE_COUNT=3
      - LICENSE_ID=bba01f94-25da-404a-a1a0-3ff087fd7497
      - SANDBOX_GATEWAY_URL=gw.sandbox.npd-co.com
      - SECURE_LINK_SECRET=700,three_high_fives_look_alive%Look_Alive
    ports:
      - "8001:8001"
    command: bash -c "make run"
    depends_on:
      - psql
      - redis
  redis:
    container_name: malware_redis
    image: redis
    ports:
      - "6380:6379"




# version: '3.7'
# services:
#   psql:
#     container_name: malware_postgres
#     image: postgres
#     environment:
#       - POSTGRES_DB=malware_analysis
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - "5432:5432"
#     restart: always
#   malware_analysis:
#     image : netpardaz/malware:1.0.3
#     # build: .
#     container_name: malware_analysis_srv
#     restart: always
#     environment:
#       - VIRUSTOTAL_APIKEY=7999f97019fda95c4565c729b137f6b51cd2afc042224eeb2485c81dab0f4187
#       - CELERY_BROKER_URL=redis://192.168.2.25:6379/1
#       - CELERY_RESULT_BACKEND=redis://192.168.2.25:6379/1
#       - POSTGRES_DB=malware_analysis
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_HOST=192.168.2.25
#       - POSTGRES_PORT=5432
#       - DAAS_MANAGER_URL=192.168.200.2:8000
#       - SCAN_DAILY_RATE_LIMIT=200
#       - ALLOWED_MALBEHAVE_COUNT=3
#     ports:
#       - "8001:8001"
#     command: bash -c "make run"
#     depends_on:
#       - psql
#       - redis
#   redis:
#     container_name: malware_redis
#     image: redis
#     ports:
#       - "6379:6379"